import { app } from "electron";
import path from "path";

import {
  AGENT_EVENT_PATH,
  AgentPermission,
  AgentQuestion,
} from "../../shared/agent-events";
import { getStateManager } from "../state";

const MAX_MESSAGE_LENGTH = 280;
const MAX_PERMISSION_DETAIL_LENGTH = 600;

export function asString(value: unknown): string {
  if (Array.isArray(value)) {
    return asString(value[0]);
  }

  return typeof value === "string" ? value.trim() : "";
}

// Cards show plain text, so drop the most common Markdown markers.
function stripMarkdown(text: string): string {
  return text
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/`([^`]*)`/g, "$1")
    .replace(/(\*\*|__)(.+?)\1/g, "$2")
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1");
}

export function truncate(text: string): string {
  const singleLine = stripMarkdown(text).replace(/\s+/g, " ").trim();

  return singleLine.length > MAX_MESSAGE_LENGTH
    ? `${singleLine.slice(0, MAX_MESSAGE_LENGTH - 1)}…`
    : singleLine;
}

// The agent's own reply can be long or private, so "finished" cards stay
// generic; the user opens the session to read it.
export function finishedMessage(label: string): string {
  return `${label} is done with this task.`;
}

export function permissionMessage(
  label: string,
  permission: AgentPermission,
): string {
  return `${label} wants to use ${permission.toolName}.`;
}

// Picks the part of the tool input that says what will actually happen.
export function parsePermission(
  toolName: string,
  toolInput: any,
): AgentPermission {
  const detail =
    asString(toolInput?.command) ||
    asString(toolInput?.file_path) ||
    asString(toolInput?.path) ||
    asString(toolInput?.url) ||
    asString(toolInput?.pattern) ||
    (toolInput && typeof toolInput === "object"
      ? JSON.stringify(toolInput, null, 1)
      : "");

  return {
    toolName,
    detail:
      detail.length > MAX_PERMISSION_DETAIL_LENGTH
        ? `${detail.slice(0, MAX_PERMISSION_DETAIL_LENGTH - 1)}…`
        : detail,
    description: asString(toolInput?.description) || undefined,
  };
}

// Accepts options as strings or { label, description }. Returns null when the
// input isn't something the balloon can answer.
export function parseQuestions(rawQuestions: unknown): AgentQuestion[] | null {
  if (!Array.isArray(rawQuestions) || rawQuestions.length === 0) {
    return null;
  }

  const questions: AgentQuestion[] = [];

  for (const raw of rawQuestions) {
    const question = asString(raw?.question);
    const options = Array.isArray(raw?.options)
      ? raw.options
          .map((option: any) =>
            typeof option === "string"
              ? { label: option.trim() }
              : {
                  label: asString(option?.label),
                  description: asString(option?.description) || undefined,
                },
          )
          .filter((option: { label: string }) => option.label)
      : [];

    if (!question || options.length === 0) {
      return null;
    }

    questions.push({
      question,
      header: asString(raw.header) || undefined,
      multiSelect: raw.multiSelect === true,
      options,
    });
  }

  return questions;
}

export function getAgentHookToken(): string {
  return getStateManager().getSettings().agentHookToken || "";
}

export function getAgentEventUrl(agentId: string): string {
  const port = getStateManager().getSettings().proactivePort || 5050;

  return `http://127.0.0.1:${port}${AGENT_EVENT_PATH}?agent=${agentId}`;
}

export function getRelayScriptPath(agentId: string): string {
  return path.join(
    app.getPath("userData"),
    "hooks",
    `officebuddies-${agentId}-hook.ps1`,
  );
}

// A PowerShell relay for agents that can only run commands as hooks. It
// forwards the hook payload from stdin to the buddy, along with the app the
// agent runs in, and prints the buddy's answer (if any) for the agent. It
// always exits 0, so a missing buddy never blocks the agent.
export function buildRelayScript(agentId: string, appProcess: string): string {
  return `# Generated by Office Buddies. Forwards ${agentId} hook events to the buddy.
try {
  # Walk up the parent processes to find the app the agent runs in.
  $hostKind = 'unknown'
  try {
    $processes = @{}
    Get-CimInstance Win32_Process -Property ProcessId, ParentProcessId, Name |
      ForEach-Object { $processes[[int]$_.ProcessId] = $_ }
    $current = $processes[[int]$PID]
    for ($depth = 0; $current -and $depth -lt 8 -and $hostKind -eq 'unknown'; $depth++) {
      switch ($current.Name.ToLowerInvariant()) {
        '${appProcess}' { $hostKind = '${agentId}-desktop' }
        { $_ -in 'code.exe', 'code - insiders.exe', 'cursor.exe', 'windsurf.exe' } { $hostKind = 'vscode' }
        { $_ -in 'windowsterminal.exe', 'wezterm-gui.exe', 'alacritty.exe', 'mintty.exe' } { $hostKind = 'terminal' }
      }
      $current = $processes[[int]$current.ParentProcessId]
    }
  } catch {
  }
  if ($hostKind -eq 'unknown') {
    if ($env:TERM_PROGRAM -eq 'vscode' -or $env:VSCODE_PID) {
      $hostKind = 'vscode'
    } elseif ($env:WT_SESSION -or $env:TERM_PROGRAM) {
      $hostKind = 'terminal'
    }
  }
  $payload = [Console]::OpenStandardInput()
  $reader = New-Object System.IO.StreamReader($payload, [System.Text.Encoding]::UTF8)
  $body = [System.Text.Encoding]::UTF8.GetBytes($reader.ReadToEnd())
  $response = Invoke-WebRequest -UseBasicParsing -Method Post -TimeoutSec 115 \`
    -Uri '${getAgentEventUrl(agentId)}' \`
    -Headers @{ Authorization = 'Bearer ${getAgentHookToken()}'; 'X-Agent-Host' = $hostKind } \`
    -ContentType 'application/json; charset=utf-8' \`
    -Body $body
  if ($response.StatusCode -eq 200 -and $response.Content) {
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    [Console]::Out.Write($response.Content)
  }
} catch {
}
exit 0
`;
}

export function toForwardSlashes(value: string): string {
  return value.replace(/\\/g, "/");
}
